### ISSUE TITLE
about your D3S

### ISSUE THREAD

**Issue by deepbrainme** [alanlukezic/csr-dcf#19]
Hello Alan,
    I'm Jesse ,  I read your paper D3S recently．　It is amazing.
Here are some confusions about your experiments in detail.
 1:How  to arrange 64 image pairs every batch to compute the foreground and background similarity channels?
2:  In Videomatch , how  the matching is perfomed in pytorch?
 Looking forward for your letter.

Best wishes,
Jesse

**Comment by alanlukezic** [comment]
Hi,
I am glad that you find our recent work interesting. I am not sure what you wanted to ask in question 1 - the image pairs are arranged into batches of dimensions: 64 x 3 x img.height x img.width. Question 2: matching of features is performed in pyTorch using tensor-multiplication operations. 
Since the paper is still under review I am closing this issue. We will make the code publicly available as soon as it is accepted.
Best,
Alan
